# Generated by Django 5.0.2 on 2024-02-23 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classApp', '0002_alter_universityclasses_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='universityclasses',
            options={'verbose_name_plural': 'University Classes'},
        ),
    ]
